apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../kube-compose.yml
    kompose.version: 1.3.0 (4f187a1)
  creationTimestamp: null
  labels:
    io.kompose.service: spark-m
  name: spark-m
spec:
  ports:
  - name: "4040"
    port: 4040
    targetPort: 4040
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "8081"
    port: 8081
    targetPort: 8081
  - name: "7077"
    port: 7077
    targetPort: 7077
  selector:
    io.kompose.service: spark-m
status:
  loadBalancer: {}
