apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../kube-compose.yml
    kompose.version: 1.3.0 (4f187a1)
  creationTimestamp: null
  labels:
    io.kompose.service: spark-s
  name: spark-s
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: spark-s
    spec:
      containers:
      - args:
        - bash
        - -c
        - start-slave.sh spark://$(SPARK_M_SERVICE_HOST):7077 ; tail -f /usr/local/spark/logs/spark*
        image: quorauk/spark-python3
        name: spark-s
        resources: {}
      restartPolicy: Always
status: {}
