apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../kube-compose.yml
    kompose.version: 1.3.0 (4f187a1)
  creationTimestamp: null
  labels:
    io.kompose.service: spark-m
  name: spark-m
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: spark-m
    spec:
      containers:
      - args:
        - bash
        - -c
        - start-master.sh ; tail -f /usr/local/spark/logs/spark*
        image: quorauk/spark-python3
        name: spark-m
        ports:
        - containerPort: 4040
        - containerPort: 8080
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
status: {}
