version: '3'
services:
  spark-master:
    image:  p7hb/docker-spark
    ports:
      - 4040:4040
      - 8080:8080
      - 8081:8081
    expose:
      - 7077
    command: bash -c "start-master.sh ; tail -f /usr/local/spark/logs/spark*"
    volumes:
      - ./.ivy2:/root/.ivy2
  spark-slave:
    image:  p7hb/docker-spark
    command: bash -c "start-slave.sh spark://spark-master:7077 ; tail -f /usr/local/spark/logs/spark*"
    volumes:
      - ./.ivy2:/root/.ivy2
  cassandra:
    image: cassandra
    expose:
      - 9042
