apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../kube-compose.yml
    kompose.version: 1.3.0 (4f187a1)
  creationTimestamp: null
  labels:
    io.kompose.service: notebook
  name: notebook
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: notebook
    spec:
      containers:
      - image: quorauk/spark-notebook-cassandra
        command: ["start-notebook.sh", "--NotebookApp.password='sha1:a0566db06985:2a9b77ee7168729d4fbae97264b2909a96449341'"]
        name: notebook
        ports:
        - containerPort: 8888
        resources: {}
        volumeMounts:
      restartPolicy: Always
status: {}
